### ISSUE TITLE
Impossible to use serialization context when not using JMS serializer

### ISSUE THREAD

**Issue by J-Ben87** [FriendsOfSymfony/FOSRestBundle#1220]
I'm not using JMS serializer, but I need to use the serialization context when handling a view.
Currently that's not possible.

I can open a PR to support that operation.

**Comment by Ener-Getick** [comment]
This is supported in FOSRestBundle 2.0 which is actually in development. You can use it at your own risks if you want with ``2.0.x-dev``.

**Comment by J-Ben87** [comment]
Oh, great news! :)
However, if you don't mind, I'll still make a PR (I'm almost done) as I need this functionnality now and in a stable version.
I hope you will find it acceptable and merge it :)

**Comment by Ener-Getick** [comment]
The problem is that it's not easy to support the symfony serializer without making BC breaks... (JMS is deeply integrated in 1.7)

If we do not accept your PR, you can use it thanks to composer ([see the docs](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository)) but you can still make use review it :-)

**Comment by J-Ben87** [comment]
You can find the PR here: https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1222
Thank you for your time anyway :)

**Comment by lsmith77** [comment]
I guess this can be closed ..
