### ISSUE TITLE
Exception_wrapper_handler under "fos_rest.user" not working

### ISSUE THREAD

**Issue by AlbertSabate** [FriendsOfSymfony/FOSRestBundle#1379]
Hi,  my problem is, that since commit: dev-master#05330bab029201c6a976da392f46a59ccb7d58b5 I have the next error:
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]    
    Unrecognized option "exception_wrapper_handler" under "fos_rest.view"

At commit dev-master#6744a48c4552285da42d1541b56351c65603ddf7 works correctly

I use view.exception_wrapper_handler to configure my exception errors.

I think that in this commit change the functionality, but i can't find the new doc, or It's a bug?

Best regards,
Albert

**Comment by Ener-Getick** [comment]
@AlbertSabate this commit replaces the ExceptionHandler by normalizers so it do not longer exist.

See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1358

**Comment by bbtdigitalkaran** [comment]
Can you please update the documentation on how to customize the error format now? I was relying on `exception_wrapper_handler` previously.

Thanks

**Comment by Ener-Getick** [comment]
As said in the documentation you can have examples in our code https://github.com/FriendsOfSymfony/FOSRestBundle/tree/master/Serializer/Normalizer.

**Comment by phoenixgao** [comment]
Hello in the documentation there's only example for people who uses symfony serializer, but no example for jms serializer,

So far what I did was created a customized ExceptionHandler which implements JMS\Serializer\Handler\SubscribingHandlerInterface and tagged as "jms_serializer.subscribing_handler", but then the first required argument is ExceptionValueMap, but I cannot inject @fos_rest.exception.messages_map to it because this services in fos rest bundle is not public.

So how could I customize my exception handler with jms serializer, without customizing all services that related, e.g. exception code map and message map?

@GuilhemN 
Thanks!
