### ISSUE TITLE
ExceptionListener ignores zone config

### ISSUE THREAD

**Issue by jovobe** [FriendsOfSymfony/FOSRestBundle#1402]
If the ExceptionListener is enabled (fos_rest.exception.enabled = true) it triggers on every route. Is this the expected behavior or did just someone forget to add something like:
![rest-bundle exceptionlistener php - core - gitrepos afw core 2016-03-22 13-35-21](https://cloud.githubusercontent.com/assets/1265894/13951687/fc776b02-f032-11e5-9ef2-ab3cec9fbf34.png)

**Comment by Ener-Getick** [comment]
I guess this was forgotten, WDYT @lsmith77 ?

**Comment by xabbuh** [comment]
Yeah, looks like it was forgotten.

@jovobe Would you like to open a pull request?

**Comment by Ener-Getick** [comment]
Fixed in #1406

**Comment by spolischook** [comment]
Why this issue is closed?
The #1406 PR add the same code as in issue and as a result Listener triggered on each exception.
Created PR https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2004
Don't know is ZONE_ATTRIBUTE will be setted for all rest queries, but hopefully tests will catch this case

**Comment by spolischook** [comment]
I broke some tests but my hand tests on work application give me a desired result - json exception on rest actions and html standard symfony exception on other routes.

**Comment by spolischook** [comment]
Found the doc https://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#zone-listener
