### ISSUE TITLE
Upgrade path to 2.0

### ISSUE THREAD

**Issue by tarjei** [FriendsOfSymfony/FOSRestBundle#1426]
Hi, how do you see the upgrade path to 2.0?

I've been working on trying to do an upgrade, and for me and my codebase there are two stumbling blocks:
- The switch to Context is not 1:1 with the old JMS api[1], but the two are so similar that I do not see why this is not the case. 
- Getting rid of Codes was a nobrainer apart from the fact that FOSCommentBundle supports Symfony 2.3 where the codes are not present in Response. I would guess there are other bundles with the same issue. Any tips to how that should be solved?

Notes:
1. For example while JMS's context has a `setGroups` that takes either an array or a string, the new Context object has addGroups and addGroup. I would like to suggest that you add a setGroups as well.

**Comment by Ener-Getick** [comment]
I think we should improve our UPGRADING file to describe how to update an existing codebase.

Our new ``Context`` class is not exactly the same as the JMS' one because some methods have unconsistent names such as ``enableMaxDepthExclusionStrategy``, this probably makes sense when we look at the jms serializer internals but for an abstraction class it should not be named that way imo.

For ``Codes``, FOSRestBundle 2.0 doesn't support sf < 2.7, so there is normally no problem and the only thing to do is to use the ``Response`` instead (the name of the constants are the same).
To maintain a generic bundle, I think the best solution is to use directly status codes (without constants) or at worst to copy-paste the class as ``@internal`` and remove it once symfony 2.3 is not supported anymore.

**Comment by Tobion** [comment]
Closing as outdated.
