### ISSUE TITLE
Warning: Header may not contain more than a single header, new line detected

### ISSUE THREAD

**Issue by mi-schi** [FriendsOfSymfony/FOSRestBundle#1693]
Hello,

when I get the exception

    \InvalidArgumentException('Every parent controller must have `get{SINGULAR}Action(\$id)` method where {SINGULAR} is a singular form of associated object')

in the line

https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Routing/Loader/Reader/RestActionReader.php#L243

Symfony can't send the response in

https://github.com/symfony/http-foundation/blob/master/Response.php#L345

The exception throwns a ContextErrorException:

    Warning: Header may not contain more than a single header, new line detected

**Solution**

Remove the \n in the exception message.

**Comment by xabbuh** [comment]
To be honest I don't understand why the exception message is sent as a header.

**Comment by mvrhov** [comment]
He probably has something in monolog turned on

**Comment by mi-schi** [comment]
No, it has nothing to do with monolog. I don't have an own monolog configuration defined. Its all default.
The header key is "X-Debug-Error". It comes from here:
https://github.com/symfony/web-profiler-bundle/commit/4a81a3f61d33417c0ad9ec73168438cae1cdde27

And the issue was already solved. I updated symfony and everything is fine :)
So the only point is the newline in the exception. I think a newline in an exception makes little sense. If you don't agree you can close the issue ;)

Thanks for your time.

**Comment by xabbuh** [comment]
Thanks for the additional info. I indeed agree that we can update the message. I just wanted to be sure that there is not bad code anywhere else that populates the header value as you will not in all other cases be sure that there are no line breaks in an exception message (so thanks for confirming that this was fixed by symfony/symfony#22154).

**Comment by aunglynn550** [comment]
wrong middleware declaration in Kernel.php also make the same error.
For example:
you declare your custom middleware inside $middleware instead of declaring inside $routeMiddleware

I did this mistake :
protected $middleware = [
\App\Http\Middleware\TrustProxies::class,
\.....................................
'approved' => \App\Http\Middleware\CheckApproved::class,
'admin' => \App\Http\Middleware\CheckAdmin::class,

];
Instead of this :

protected $routeMiddleware = [
'auth' => \App\Http\Middleware\Authenticate::class,
\........................
'approved' => \App\Http\Middleware\CheckApproved::class,
'admin' => \App\Http\Middleware\CheckAdmin::class,
];

I really hope this will help you

**Comment by zabi-hac** [comment]
it incorrect, My custom middleware was at $routeMiddleware  but it have same error.
