### ISSUE TITLE
REST API documentation generation out of routes

### ISSUE THREAD

**Issue by everzet** [FriendsOfSymfony/FOSRestBundle#20]
Analyze defined routes and generate REST API documentation out of it (maybe with view layer configuration involved - acceptable formats)

**Comment by oliver-ignitiondigital** [comment]
I know this is very old, but some things changed since then and I found this relatively quickly whilst looking for a package/bundle for Swagger / Openapi.
Any chance to reconsider this? Since the NelmioApiDocBundle is abandoned and I can't see any real alternative that integrates into Symfony for Swagger / OpenApi (or any other really, RAML, ...?).
