### ISSUE TITLE
Exception controller support in version 3

### ISSUE THREAD

**Issue by pavlepredic** [FriendsOfSymfony/FOSRestBundle#2247]
[This document](https://symfony.com/doc/master/bundles/FOSRestBundle/4-exception-controller-support.html) demonstrates how to register an exception controller, but [this one](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3.x/UPGRADING-3.0.md) states that `fos_rest.exception.exception_controller` configuration option has been removed. What gives? Is the support for custom exception controllers completely dropped in version 3 and if so, what is the alternative?

**Comment by GinoPane** [comment]
Same here!
The documentation says that exception_controller is still there, but the application gives the following error:

```
Unrecognized option "exception_controller" under "fos_rest.exception". Available options are "codes", "debug", "enabled", "exception_listener", "flatten_exception_format", "map_exception_codes", "messages", "serialize_exceptions", "serializer_
  error_renderer".
```

It's also interesting that `exception_listener` is also listed as removed in CHANGELOG, but it is still available in error message.

So, what to use instead of `exception_controller`? And how to migrate the config like this?

![image](https://user-images.githubusercontent.com/3897579/85785724-3db8f200-b732-11ea-817f-7e6b5ab2d218.png)

**Comment by xabbuh** [comment]
I have opened #2252 to remove the docs for these deprecated/removed options. The bundle now relies on the Symfony error renderer to take care of rendering the response. For API endpoints you can customize  the responses with a custom normalizer (when using the Symfony Serializer component) or with a custom handler (when using the JMS Serializer).
