### ISSUE TITLE
Documentation is borked

### ISSUE THREAD

**Issue by CJDennis** [FriendsOfSymfony/FOSRestBundle#2329]
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3.x/Resources/doc/index.rst is borked. None of the links work.

Other pages have similar issues. External links work, but all internal links seem to be borked.

**Comment by mbabker** [comment]
The docs were written to be included on `symfony.com`.  With the new bundles documentation section, this bundle is no longer listed.

Assuming [new maintainers are found](https://twitter.com/lsmith/status/1440216817876627459?s=21), I'd suggest the docs be updated to be usable on GitHub (i.e. rewritten as Markdown instead of RST).

**Comment by Th3Mouk** [comment]
I can't find the issue, but this have already being discussed. The documentation has been unlist from `symfony.com` due to format changes. They are opened to relist this bundle on the website, but we must first of all comply to the new format.

**Comment by W0rma** [comment]
@goetas What's your opinion here? Should we try to get the documentation back to `symfony.com` or should we rather switch to plain Markdown files?

**Comment by goetas** [comment]
@W0rma  do you have a guess on how much work is needed? Are available the new documentation rules? 

having the docs on `symfony.com` would be nice, it just depends on how much work is needed.

**Comment by W0rma** [comment]
> do you have a guess on how much work is needed? Are available the new documentation rules?

In know the [documentation format](https://symfony.com/doc/current/contributing/documentation/format.html)  but I don't know if there are special requirements for bundle documentation.

@javiereguiluz Do you have some hints what should be done in order to get the documentation of this bundle back to `symfony.com`? I'd be glad to help here.

**Comment by javiereguiluz** [comment]
@W0rma as @mbabker said, this bundle is no longer listed on symfony.com. There was an internal debate about which bundles to add/keep/remove and it was decided to remove this one in favor of promoting the usage of API Platform.

I know this can be disappointing, but please keep in mind that this decision is not about judging the technical merits of each bundle. Thanks!

**Comment by goetas** [comment]
will be solved by https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2348
