### ISSUE TITLE
The future of FOSRestBundle

### ISSUE THREAD

**Issue by W0rma** [FriendsOfSymfony/FOSRestBundle#2336]
I read in https://twitter.com/lsmith/status/1440216817876627459 that there are plans to deprecate this bundle because the current maintainers are for various reason no longer able to contribute.

@xabbuh @GuilhemN @lsmith77 Have you already found new maintainers for this bundle?

**Comment by lsmith77** [comment]
not yet .. there was one person that expressed via interest and another via slack .. but nothing concrete has materialized .. best would be to join #fostrestbundle on symfony slacck to discuss further.

**Comment by goetas** [comment]
Hello all. 

I'm the maintainer of `jms/serializer` and i could step up and try to help to maintain this bundle. I'm using it in most of my projects at work already. I'm not familiar with all the parts of fostrestbundle but i have a general feeling on how works most of it, and a more deep knowledge of the components that are dealing with serialization and error handling.

**Comment by flohw** [comment]
Hello there,

I am interested too as this is a bundle we use for a large project (7 years) and switching to API Platform would be... Interesting.

Maybe as a co-maintainer to begin as it would be the open source project for me and not really aware how the bundle is deeply built but I can learn :-)

In any case, thank you for your amazing work and taking time to upgrade to support SF4 we would had a hard time otherwise.

**Comment by lsmith77** [comment]
great to hear!

I have granted @goetas push access to the repository since I already know him from the work he has done on other Symfony bundles. Once things have settled in, I am then happy to give will admin rights.

If in the meantime it becomes clear that efficient work requires that additional people need access, I am happy to discuss this.

**Comment by goetas** [comment]
Hi all.
@lsmith77 thanks for the trust.
I started to try locally some of the pending pull request and to look at the various issues. I think that it will take me some time before I actually can find time to merge confidently some new code, but that's my goal. 🤞I hope to find a day or two to dig deeper into it

**Comment by goetas** [comment]
We had already two new releases and the work on the next release is going on. I thin that for now this is solved :)
