### ISSUE TITLE
Think about how to deal with flash messages

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSRestBundle#25]
A common use case will be adding/editing some resource via Ajax/Ajaj. In this scenario the request will probably return a 200/201 with an url from where the created/edited resource can be GET. Now the flash message should be displayed once the content from the created/edited resource is fetched and displayed. Maybe it would make more sense to write flash messages into a cookie allowing the client to manage (read and remove) flash messages? With a custom rule to ignore the "flash message" cookie for caching it should also be ESI friendly.

**Comment by docteurklein** [comment]
@lsmith77 I know it's an old issue, and I will open a new one if necessary, but:

Currently flash messages have been moved to FOSHttpCache.
Unfortunatly, it's a all or nothing choice. If activated, the flash listnener will move all flashes oute of the session and put them in a cookie.

The cookie idea might be ok, but I think we should make a distinction between templated responses and non templated ones.

For example, depending on `$viewHandler->isFormatTemplating($format)`, we either keep the standard behavior (keep it in session, "render and forget" on next response, and respect https://en.wikipedia.org/wiki/Post/Redirect/Get), or we move them in headers (ajax and co).

I propose to introduce the idea of flash messages in the `View` api, so that the view handler impl can decide what to do.

Thoughts?
