### ISSUE TITLE
Dupplicate route

### ISSUE THREAD

**Issue by pmithrandir** [FriendsOfSymfony/FOSRestBundle#813]
Hello

When I create a route with a REST\GET annotation, I'm getting it in double in my route list.

Exemple : 

```
/**
    * @ApiDoc(
    *   section = "photo",
    *   resource = true,
    *   description = "Search one photo",
    *   output="Orange\Exif\CoreBundle\Entity\Photo",
    *   statusCodes = {
    *     200 = "Returned when successful",
    *     404 = "Returned when no photo had been found"
    *   },
    * requirements={
    *      {
    *          "name"="hash",
    *          "dataType"="integer",
    *          "requirement"="\d+",
    *          "description"="the CRC32 hash of the Photo"
    *      },
    *      {
    *          "name"="filesize",
    *          "dataType"="integer",
    *          "requirement"="\d+",
    *          "description"="the size hash of the Photo in octet"
    *      },
    *  },
    * )
    * @Rest\Get("/photos/{hash}/{filesize}")
    * @Rest\View()
    */
    public function searchAction($hash, $filesize) {
        $photo = $this->getDoctrine()->getRepository('OrangeExifCoreBundle:Photo')->findOneBy(array("hash" => $hash, "filesize" => $filesize));
        if (!is_object($photo)) {
            throw $this->createNotFoundException();
        }
        return $photo;
    }
```

Give me : 

```
 exif_core_photos_search GET    ANY    ANY  /photos/{hash}/{filesize}                    
 search_photos                  GET    ANY    ANY  /api/photos/{hash}/{filesize}.{_format}
```

If I put in the GET annotation /api/ I get the same issue, but with a generated url like /api/api/photos...
If I add the format at the end of the url, I get it doubled(and an error occured)

Any idea why ?

I saw different issue related to duplicate, but they don't seem to be identical, and they were supposed to be resolved in april. I'm using dev-master branch.

Pierre

**Comment by vrobinsonscs** [comment]
And old and closed issue, but was the closest discussion I came across in dealing with the same thing, and I came up with something maybe helpful to others.

I had a method `getPersonsAction()` to which I wanted to add an option for parameters, so it would *optionally* match `/persons/{options}` as well as `/persons`.

Adding `@NoRoute` only caused the duplicated route entry to match '/' (i.e., stripped out the rest of the route's path), but left the duplicated entry in the routes table. Tried lots of combinations of enabling and disabling prefixes in routing.yml files, FOSRest Route and Get bundles (vs. Sensiolabs versions), etc. Finally hit on the winning combination:

```
    /*
     * @Route("/persons/{options}", name="get_persons_options", options={"method_prefix" = false}, methods={"GET"}, defaults={"options"=""})
     */
    public function getPersonsOptions($options) {
        // code....
    }
```

The trick was simply to remove 'Action' from the method name, changing `getPersonsAction($options)` to `getPersonsAnythingatall($options)`. (I chose 'Options.')

Since FOSRestBundle keys off the 'Action' segment of the name, it's got nothing to work with except the manually declared route, and so does not create a duplicate (at least, that's my interpretation).

Voila!
