### ISSUE TITLE
Why does an options action not pluralize?

### ISSUE THREAD

**Issue by NicParry** [FriendsOfSymfony/FOSRestBundle#911]
```
/**
 * @FOS\RouteResource("Thing")
 */
class ThingController extends FOSRestController implements ClassResourceInterface
{
    public function cgetAction()
    {
        //results in /things
    }
    public function postAction()
    {
        //results in /things
    }
    public function optionsAction()
    {
        //results in /thing
    }
}
```

I don't mind the pluralization, but it needs to be consistent, so I think this might be a bug

**Comment by lsmith77** [comment]
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/941

**Comment by deeky666** [comment]
@lsmith77 actually I don't quite get the intention of having `OPTIONS` only available for `/resources` as the [RFC](https://tools.ietf.org/html/rfc2616#page-52) says `OPTIONS` requests `SHOULD` include the `Allow` header in the response to be able to determine which HTTP methods are allowed on the particular resource (and this is what I was always having in mind so far). So IMO this method should also apply for singular resources.
Imagine having relational links in an entity response. Instead of having the HTTP method included explicitly:

```json
[
    {
        "href": "/users/1",
        "rel": "show_user",
        "method": "GET"
    },
    {
        "href": "/users/1",
        "rel": "replace_user",
        "method": "PUT"
    },
    {
        "href": "/users/1",
        "rel": "delete_user",
        "method": "DELETE"
    },
]
```
I would rather have one single link to `/users/1` and let the user discover available HTTP methods via `OPTIONS` instead. This shrinks the response a lot and makes it also "cleaner".
What do you think?

**Comment by lsmith77** [comment]
hmm I do not remember my motivations back then .. but yeah I see no reason not to allow OPTIONS requests for singular resources.
