### ISSUE TITLE
Documentation Links Broken

### ISSUE THREAD

**Issue by mddubs** [FriendsOfSymfony/FOSRestBundle#931]
Hi, browsing the documentation through the Github repo seems to have broken in only the last couple of days.  Screenshot attached.
![screen shot 2015-01-11 at 11 53 37 am](https://cloud.githubusercontent.com/assets/366233/5695966/b6de8a00-9988-11e4-86a1-4d52a099c8ed.png)

**Comment by merk** [comment]
Thanks for reporting. This is intentional: the documentation for this bundle is moving to symfony.com. https://github.com/FriendsOfSymfony/FOSRestBundle/pull/930

In the mean time, you can view documentation by using the 1.5.0-RC3 tag here:

https://github.com/FriendsOfSymfony/FOSRestBundle/blob/1.5.0-RC3/Resources/doc/index.md

**Comment by lsmith77** [comment]
@javiereguiluz any ETA here? I would like to make the stable release now .. so it would be good to have a proper URL to point to
